--- 
- name: DB2 client uninstall
  hosts: "{{ envir }}:&dev"
  gather_facts: yes 
  become: true
  become_method: sudo
  vars_files:
    # - vars_files/{{ inventory_hostname }}/dev.yml
    - vars_files/main.yml
  roles: 
    - db2_client_uninstall
  tags: db2uninstall 