---
db2_instances:
        - instance: "DB2INST2"
          name: "db2inst2"
          group_name: "db2iadm2"
          home_directory: "/opt/db2/db2inst2"
          options:
            autostart: "YES"
            start_during_install: "YES"