---
- name: move the "{{ user_name }}" instance to "{{ standard_user }}"...
  command: mv "{{ db2_inst_home }}"/sqllib /home/"{{ standard_user }}/sqllib" 
  register: db2_rename_instance

- name: Print rename instance output...
  debug:
    msg: "{{ db2_rename_instance }}" 

- name: recursively update /home/{{ standard_user }}/sqllib directory owner
  file:
    path: /home/{{ standard_user }}/sqllib
    state: directory
    recurse: yes
    owner: "{{ standard_user }}"

- name: replace line DB2INSTANCE={{ user_name }} in /home/{{ standard_user }}/sqllib/db2profile
  lineinfile: 
    path: /home/{{ standard_user }}/sqllib/db2profile 
    regexp: '^(.*)DB2INSTANCE={{ user_name }}(.*)$' 
    line: 'DB2INSTANCE={{ standard_user }}'
    backrefs: yes
  

- name: replace line "{{ standard_user }}" in /home/{{ standard_user }}/sqllib/db2profile
  lineinfile: 
    path: /home/{{ standard_user }}/sqllib/db2profile 
    regexp: '^(.*)INSTHOME=/home/{{ user_name }}(.*)$' 
    line: 'INSTHOME=/home/{{ standard_user }}'
    backrefs: yes
  
- name: replace line DB2INSTANCE={{ user_name }} in /home/{{ standard_user }}/sqllib/db2cshrc
  lineinfile: 
    path: /home/{{ standard_user }}/sqllib/db2cshrc 
    regexp: '^(.*)setenv DB2INSTANCE {{ user_name }}(.*)$' 
    line: 'setenv DB2INSTANCE {{ standard_user }}'
    backrefs: yes
  

- name: replace line "{{ standard_user }}" in /home/{{ standard_user }}/sqllib/db2cshrc
  lineinfile: 
    path: /home/{{ standard_user }}/sqllib/db2cshrc 
    regexp: '^(.*)setenv INSTHOME /home/{{ user_name }}(.*)$' 
    line: 'setenv INSTHOME /home/{{ standard_user }}'
    backrefs: yes

- name: move the /home/{{ standard_user }}/sqllib instance to "{{ db2_home }}"...
  command: mv /home/{{ standard_user }}/sqllib "{{ db2_home }}/sqllib"
  register: db2_instance_move
  
- name: recursively update "{{ db2_home }}"/sqllib directory owner
  file:
    path: "{{ db2_home }}/sqllib"
    state: directory
    recurse: yes
    owner: "{{ standard_user }}"
  
- name: Print instance move to "{{ db2_home }}" output...
  debug:
    msg: "{{ db2_instance_move }}" 
  
- name: Validating DB2 
  command: "{{ db2_home }}/sqllib/bin/db2val -o"
  register: db2_val
  
- name: Validate results
  debug: var=db2_val

- name: Drop db2 instance "{{ user_name }}"
  command: "{{ db2_instance_path }}/db2idrop {{ user_name }}"
  register: db2_instance_drop
  ignore_errors: yes
  tags: test 

- name: Print DB2 drop output
  debug:
    msg: "{{ db2_instance_drop }}"
  tags: test

- name: Remove "{{ user_name }}" user
  user:
    name: "{{ user_name }}"
    state: absent
    remove: yes 
  tags: test