---
# - name: Create new instance home path "{{ standard_user }}"...
#   file: 
#    path: "{{ item }}"
#    state: directory 
#    mode: 0755
#    owner: standard_user
#    group: db2inst1
#   with_items:
#     - /home/"{{ standard_user }}"

# - name: Create new instance home path "{{ standard_user }}"...
#   command: mkdir /home/"{{ standard_user }}" 
#   register: db2_instance_dir

# - name: Print new instance home path output...
#   debug:
#     msg: "{{ db2_instance_dir }}" 

- name: move the "{{ user_name }}" instance to "{{ standard_user }}"...
  command: mv "{{ db2_inst_home }}"/sqllib /home/"{{ standard_user }}/sqllib" 
  register: db2_rename_instance

- name: Print rename instance output...
  debug:
    msg: "{{ db2_rename_instance }}" 

- name: recursively update /home/{{ standard_user }}/sqllib directory owner
  file:
    path: /home/{{ standard_user }}/sqllib
    state: directory
    recurse: yes
    owner: "{{ standard_user }}"

- name: replace line DB2INSTANCE={{ user_name }} in /home/{{ standard_user }}/sqllib/db2profile
  lineinfile: 
    path: /home/{{ standard_user }}/sqllib/db2profile 
    regexp: '^(.*)DB2INSTANCE={{ user_name }}(.*)$' 
    line: 'DB2INSTANCE={{ standard_user }}'
    backrefs: yes
  

- name: replace line "{{ standard_user }}" in /home/{{ standard_user }}/sqllib/db2profile
  lineinfile: 
    path: /home/{{ standard_user }}/sqllib/db2profile 
    regexp: '^(.*)INSTHOME=/home/{{ user_name }}(.*)$' 
    line: 'INSTHOME=/home/{{ standard_user }}'
    backrefs: yes
  

- name: move the /home/{{ standard_user }}/sqllib instance to "{{ db2_home }}"...
  command: mv /home/{{ standard_user }}/sqllib "{{ db2_home }}/sqllib"
  register: db2_instance_move
  

- name: Print instance move to "{{ db2_home }}" output...
  debug:
    msg: "{{ db2_instance_move }}" 
  
- name: Validating DB2 
  command: "{{ db2_home }}/sqllib/bin/db2val -o"
  register: db2_val
  tags: test

- name: Validate results
  debug: var=db2_val
  tags: test
