---
- name: Unarchive the db2 packages on target server
  unarchive:
    src: "{{ tmp_dir }}/{{ db2_package }}"
    dest: "{{ tmp_dir }}/db2"
    remote_src: yes 
    force: yes   

- name: Drop db2 instance "{{ user_name }}"
  command: "{{ db2_instance_path }}/db2idrop {{ user_name }}"
  register: db2_instance_drop

- name: Print DB2 drop output
  debug:
    msg: "{{ db2_instance_drop }}"

- name: Execute the db2 client installation
  command: "{{ tmp_dir }}/db2/client/db2_deinstall -r {{ tmp_dir }}/db2/client/db2un.rsp -b {{ db2_home_path }}"
  register: db2_instance_uninstall

- name: Print DB2 level output
  debug:
    msg: "{{ db2_instance_uninstall }}"

