---
- name: Drop db2 instance "{{ user_name }}"
  command: "{{ db2_instance_path }}/db2idrop {{ user_name }}"
  register: db2_instance_drop

- name: Print DB2 drop output
  debug:
    msg: "{{ db2_instance_drop }}"
  fail:
    msg: "No DB2 instance skipping..."
  when: "db2_instance_drop.rc == 1"

