---
# resp:
#    PROD: "CLIENT"
#    FILE: "/opt/ibm/db2/V10.5"
#    LIC_AGREEMENT: "ACCEPT" # ACCEPT or DECLINE
#    INSTALL_TYPE: "TYPICAL" # TYPICAL, COMPACT, CUSTOM

db2_package: v11.1.4fp6_linuxx64_client.tar.gz
tmp_dir: /tmp
db2_install_dir: /opt
db2_home_path: /opt/ibm/db2/v11.1.4 
user_name: db2inst1
group_name: db2inst1
envir: dev

# Response file keywords: https://www-01.ibm.com/support/knowledgecenter/SSEPGG_10.5.0/com.ibm.db2.luw.qb.server.doc/doc/r0007505.html
resp:
  PROD: "CLIENT"
  FILE: "/opt/ibm/db2/V11.1"
  LIC_AGREEMENT: "ACCEPT" # ACCEPT or DECLINE
  INSTALL_TYPE: "TYPICAL" # TYPICAL, COMPACT, CUSTOM

db2_instances:
  #Those five params are mandatory to create a DB2 instance
  - instance: "DB2INST"
    name: "db2inst1"
    options:
            autostart: "YES" # YES or NO
            start_during_install: "YES" # YES or NO

# Create the instances listed in 'db2_instances' variable.
# This can be set to false for installation without any instance.
create_instances: true