
db2_package: v11.5.4_linuxx64_client.tar.gz
tmp_dir: /tmp
db2_install_dir: /opt
db2_home_path: /opt/ibm/db2/v11.1.4 
user_name: db2inst12345
group_name: db2inst12345
envir: dev
db2_instance_path: /opt/ibm/db2/v11.1.4/instance
db2_package_dir: /tmp/db2

resp:
  prod: "CLIENT"
  file: "/opt/ibm/db2/v11.1.4"
